management:
  application:
    name: GithubScore
    description: A backend application for scoring GitHub repositories based
    author: Sohrab Rahmani
    version: '@project.version'

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
        dialect: ${SPRING_JPA_HIBERNATE_DIALECT}
  profiles:
    active: dev

github:
  api:
    url: https://api.github.com