spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/githubscore_db
    username: githubscore_user
    password: githubscore_password
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
        ddl-auto: create-drop
github:
  api:
    url: https://api.github.com